# All services starts from here
services:
  elasticsearch:
    # Official elasticsearch docker image from ES
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.1-amd64
    platform: linux/amd64
    # Human-readable container name
    container_name: elasticsearch
    # Environment variables inside containers
    environment:
    # Using as a single node
      - discovery.type=single-node
    # Disable security
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=basic
    ports:
    # Port Mapping
      - "9200:9200"
    networks:
    # Allow containers to communicate
      - elk

  kibana:
    # Official kibana docker image from ES
    image: docker.elastic.co/kibana/kibana:9.4.1-amd64
    platform: linux/amd64
    # Container name
    container_name: kibana
    # Environment variables inside kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
    # Port Mapping
      - "5601:5601"
    # Start Elasticsearch before kibana
    # Prevent kibana startup failure
    depends_on:
      - elasticsearch
    # Allowing different containers to communicate
    networks:
      - elk

  filebeat:
    # Official Filebeat docker image from ES
    image: docker.elastic.co/beats/filebeat:9.4.1-amd64
    platform: linux/amd64
    #Container name
    container_name: filebeat
    # Permissions
    user: root
    # Place to read logs
    command: ["--strict.perms=false"]
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/logs:ro
      - /var/log/auth.log:/hostfs/var/log/auth.log:ro
    depends_on:
    # Dependencies
      - elasticsearch
    # Inside network communication
    networks:
      - elk

  logstash:
    # Logstash docker image
    image: docker.elastic.co/logstash/logstash:9.4.1-amd64
    # Container name
    container_name: logstash
    # Port mapping
    ports:
      - "5044:5044"
    # Volume for pipeline
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    # Communication between networks
    networks:
      - elk
    # First run ES then depending
    depends_on:
      - elasticsearch

networks:
  elk: 