input {
    beats {
        port => 5044
    }
}

filter {
    grok {
        match => {
            "message" => "Failed password for %{USERNAME:user.name} from %{IP:source.ip}"
        }
    }

    if "Failed password" in [message] {
        mutate {
            add_field => {
                "[event][action]" => "failed_login"
            }
        }
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "logs-%{+YYYY.MM.dd}"
    }

    stdout {
        codec => rubydebug
    }
}